# jekyll theme
theme: null

# site properties and page defaults
title: Stujenske Lab
subtitle: Studying the Cognitive Regulation of Internal States
description: The Official Website of the Stujenske Lab
header: images/background.jpg
footer: "" #images/background.jpg
header_gif: images/background.gif
header_city_dark: _styles/images/pittsburgh_background.jpg
header_city: _styles/images/Pittsburgh_day.jpg
header-dark: true
logo-text: true

# site social media and other links
links:
  email: stujenske.lab@gmail.com
  orcid: 0000-0002-5188-717X
  google-scholar: Rj1TCzUAAAAJ
  github: Stujenske-lab
  twitter: jmstujenske
#  youtube: YourLabChannel

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: main_page
  # markdown files in /_lab
  - scope:
      path: "lab"
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # markdown files in /team
  - scope:
      path: "team"
    values:
      layout: default
  # markdown files in /research
  - scope:
      path: "publications"
    values:
      layout: default
  # markdown files in /contact
  - scope:
      path: "contact"
    values:
      layout: default
  # markdown files in /blog
  #- scope:
  #    path: "blog"
  #  values:
  #    layout: default
  # markdown files in /tools
  - scope:
      path: "tools"
    values:
      layout: default
  # markdown files in /projects
  - scope:
      path: "projects"
    values:
      layout: default

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
  - _posts
  - tmp