theme: null
title: Stujenske-Lab
subtitle: Studying the Cognitive Regulation of Internal States
description: An engaging 1-3 sentence description of your lab.
header: images/background.jpg
footer: ""
header_gif: images/background.gif
header_city_dark: _styles/images/pittsburgh_background.jpg
header_city: _styles/images/Pittsburgh_day.jpg
header-dark: true
logo-text: true
links:
  email: stujenske.lab@gmail.com
  orcid: 0000-0002-5188-717X
  google-scholar: Rj1TCzUAAAAJ
  github: Stujenske-lab
  twitter: jmstujenske
defaults:
  - scope:
      path: ""
    values:
      layout: main_page
  - scope:
      path: lab
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      path: team
    values:
      layout: default
  - scope:
      path: publications
    values:
      layout: default
  - scope:
      path: contact
    values:
      layout: default
  - scope:
      path: tools
    values:
      layout: default
  - scope:
      path: projects
    values:
      layout: default
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
  - _posts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
  - _posts/
  - tmp/
  - blog/
email: contact@Stujenske-Lab.com
github: Stujenske-Lab
twitter: Stujenske-Lab
instagram: Stujenske-Lab
youtube: Stujenske-Lab
