- id: pubmed:35397211
  image: images/Neuron2022_abstract.png
  buttons:
    - type: github
      link: https://github.com/jmstujenske/PL_drives_nonaversion_via_SOM_IN
 
- id: pubmed:28761080
  image: images/Garcia2017.png
 
- id: pubmed:28542155
  image: images/FearBottom.png
 
- id: pubmed:28481349
  image: images/Bolkan.png
 
- id: pubmed:26166563
  image: images/Heat.png
  buttons:
    - type: github
      link: https://github.com/jmstujenske/Spatiotemporal-Dynamics-Fiber-Optic

- id: pubmed:26140594
  image: images/Gore.png
 
- id: pubmed:25144877
  image: images/ThetaGamma.png
 
- id: pubmed:24241397
  image: images/Likhtik.png
 
- id: pubmed:21460263
  image: images/zebrafish.png
 