- id: pubmed:35397211
  image: http://stujenske-lab.github.io/images/Neuron2022_abstract.png
 
- id: pubmed:28761080
  title: Serotonin inputs to the dorsal BNST modulate anxiety in a 5-HT
  
- id: pubmed:28542155
  title: Fear from the bottom up.
 
- id: pubmed:28481349
  title: Thalamic projections sustain prefrontal activity during working memory maintenance.
  
- id: pubmed:26166563
  title: Modeling the Spatiotemporal Dynamics of Light and Heat Propagation for In
    Vivo Optogenetics.
  
- id: pubmed:26140594
  title: Neural Representations of Unconditioned Stimuli in Basolateral Amygdala Mediate
    Innate and Learned Responses.
 
- id: pubmed:25144877
  title: Fear and safety engage competing patterns of theta-gamma coupling in the
    basolateral amygdala.
 
- id: pubmed:24241397
  title: Prefrontal entrainment of amygdala activity signals safety in learned fear
    and innate anxiety.
 
- id: pubmed:21460263
  title: The bugeye mutant zebrafish exhibits visual deficits that arise with the
    onset of an enlarged eye phenotype.
 